### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [Victoromoniyi/GNULiteX#3]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by Victoromoniyi** [comment]
Hi Mithro,

Thanks for this. Just added it now.

**Comment by mithro** [comment]
Just FYI, most of the LiteX ecosystem is released under the two-clause BSD license (see https://github.com/enjoy-digital/litex/blob/master/LICENSE). By choosing to use the GPL license it means that nothing for this repository can be merged into the upstream repositories.

**Comment by Victoromoniyi** [comment]
Hi Tim,

Thanks for pointing that out. I've now changed it.

**Comment by dkozel** [comment]
@mithro This code must be GPL (or compatible) as it directly inherits in code from GNU Radio which is GPL. The source files already include SPDX identifiers, though a cleanup round is needed to make the author info verbose.
https://github.com/Victoromoniyi/gr-litex/blob/master/include/litexgnu/litexgnu.h#L5
https://github.com/Victoromoniyi/gr-litex/blob/master/lib/litexgnu_impl.h#L5

The BSD code from LiteX is used as a library, currently included in-tree for speed of development, but soon to be moved to an external library. Work on packaging the userspace and kernel portions is here:
https://github.com/dkozel/liblitepcie

The LitePCIe driver and kernel modules are BSD, which can be used in a GPL project.
https://github.com/Victoromoniyi/gr-litex/blob/master/litepcie/litepcie/software/user/liblitepcie.h#L7
https://github.com/Victoromoniyi/gr-litex/blob/master/litepcie/litepcie/software/kernel/litepcie.h#L7

Victor, sorry for the fuss, but the overall project license correctly is GPL 3.0 or later.

**Comment by dkozel** [comment]
Resolved in https://github.com/Victoromoniyi/gr-litex/commit/3906f4117c45540ed8bb587090d3ff96bdfcb798
