### ISSUE TITLE
Add GNU Radio 3.8 support

### ISSUE THREAD

**Issue by alphafox02** [Victoromoniyi/GNULiteX#6]
Looking forward to the presentation, just wondered if it’ll be possible to backport and/or have a GR 3.8 branch? Would love to see it included in DragonOS. Thank you.

**Comment by dkozel** [comment]
@alphafox02 Hi, I don't think that Victor or I will implement that, but the maint-3.9 and main branches are compatible with GNU Radio 3.10 as well so if/when Dragon OS moves to Ubuntu 22.04 this module is ready to go.

**Comment by alphafox02** [comment]
Completely understandable. I’ll definitely look at rebuilding DragonOS down the road on the next LTS release!
